"""Constants for the Go-On UTOR-RKY20-N7-1 Aircon IR integration."""

DOMAIN = "aircon_ir"

CONF_DEFAULT_FAN_MODE = "default_fan_mode"
CONF_DEFAULT_TEMPERATURE = "default_temperature"
CONF_MAX_TEMP = "max_temp"
CONF_MIN_TEMP = "min_temp"
CONF_REMOTE_ENTITY_ID = "remote_entity_id"
CONF_INFRARED_ENTITY_ID = "infrared_entity_id"
CONF_REPEATS = "repeats"

DEFAULT_FAN_MODE = "low"
DEFAULT_MAX_TEMP = 30
DEFAULT_MIN_TEMP = 16
DEFAULT_NAME = "Go-On UTOR-RKY20-N7-1 Aircon IR"
DEFAULT_REPEATS = 1
DEFAULT_TEMPERATURE = 23

FAN_MODE_HIGH = "high"
FAN_MODE_LOW = "low"
FAN_MODES = [FAN_MODE_LOW, FAN_MODE_HIGH]

SWING_OFF = "off"
SWING_ON = "on"
SWING_MODES = [SWING_OFF, SWING_ON]
CONF_DEFAULT_SWING_MODE = "default_swing_mode"
DEFAULT_SWING_MODE = SWING_OFF
